VS2017 support
OlivierGuinart/Merlin32Language pull request #4
Opened 2017-09-23 03:11 UTC by BrianPeek

Very quick and dirty update for VS2017 support.  "It works on my machine".  Should still support VS2013/15 with these changes, but requires VS2017 to build.

2017-09-23 17:54 UTC, OlivierGuinart commented
Great timing Brian (https://twitter.com/OlivierGuinart/status/896499395314581505)! I’ll get on your PR asap.

Thanks!

Olivier.

From: Brian Peek [mailto:notifications@github.com]
Sent: Friday, September 22, 2017 8:12 PM
To: OlivierGuinart/Merlin32Language <Merlin32Language@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [OlivierGuinart/Merlin32Language] VS2017 support (#4)


Very quick and dirty update for VS2017 support. "It works on my machine". Should still support VS2013/15 with these changes, but requires VS2017 to build.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/OlivierGuinart/Merlin32Language/pull/4

Commit Summary

  *   VS2017 support

File Changes

  *   M Merlin32Language.csproj<https://github.com/OlivierGuinart/Merlin32Language/pull/4/files#diff-0> (87)
  *   M Merlin32Language.sln<https://github.com/OlivierGuinart/Merlin32Language/pull/4/files#diff-1> (13)
  *   M Resources/data.Designer.cs<https://github.com/OlivierGuinart/Merlin32Language/pull/4/files#diff-2> (2)
  *   M Resources/directives.Designer.cs<https://github.com/OlivierGuinart/Merlin32Language/pull/4/files#diff-3> (2)
  *   M Resources/opcodes.Designer.cs<https://github.com/OlivierGuinart/Merlin32Language/pull/4/files#diff-4> (2)
  *   M source.extension.vsixmanifest<https://github.com/OlivierGuinart/Merlin32Language/pull/4/files#diff-5> (49)

Patch Links:

  *   https://github.com/OlivierGuinart/Merlin32Language/pull/4.patch
  *   https://github.com/OlivierGuinart/Merlin32Language/pull/4.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/OlivierGuinart/Merlin32Language/pull/4>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ALe73f1o2pJrGe41fk71UXiWibARsxVEks5slHbsgaJpZM4PhbE9>.

2017-09-23 18:02 UTC, BrianPeek commented
The Shell.12.0 thing is a bit hacky (using a NuGet package someone created that has the proper DLL in it).  You can perhaps avoid NuGet by using a redirection as described here:  https://msdn.microsoft.com/en-us/magazine/mt493251.aspx but I haven't tested this.  Happy to help if there's something else I can do!  :)

Overall, I was just looking for 6502 syntax highlighting...using cc65 assembler and tools in a project, but this is close enough!

2017-09-23 19:07 UTC, OlivierGuinart requested changes
Small stuff:
- many references not needed
- you can get away from the shell.12 thingy by going to shell.15 (and I don't mind nuget packages, at the contrary in fact).
- time to increment the extension version with its first update ever you're bringing in! :)

2017-09-23 19:07 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="Microsoft.VisualStudio.Threading, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
Not needed? Wasn't found on opening the solution, removed it, no side effects.

2017-09-23 19:07 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="Microsoft.VisualStudio.GraphModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
Not needed? Wasn't found on opening the solution, removed it, no side effects

2017-09-23 19:07 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="envdte, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
Not needed? Removed it, no side effects

2017-09-23 19:07 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="stdole, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
Not needed? Removed it, no side effects

2017-09-23 19:07 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="System.Transactions" />
Not needed.

2017-09-23 19:07 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="System.Xml.Linq" />
Not needed? Removed it, no side effects

2017-09-23 19:07 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <None Include="packages.config" />
Not found in your branch but not needed either AFAICT. This can also be removed safely.

2017-09-23 19:07 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
I saw your other comment on the conversation thread. What I just did that worked: remove this reference from your project, and add the Microsoft.VisualStudio.Shell.15.0 one (your VS build and target anyway). VS will complain about .net framework targets (valid complain :)), but just retarget the project (Project Properties\Application\Target framework) to .net framework 4.6 and you'll then be in a clean state again.

2017-09-23 19:07 UTC, OlivierGuinart commented on Merlin32Language.sln
> -	GlobalSection(TeamFoundationVersionControl) = preSolution
Thank you for removing this section! 👍 Was on my todo list 😊

2017-09-23 19:07 UTC, OlivierGuinart commented on source.extension.vsixmanifest
> +        <Identity Id="Merlin32Language..c729d6b2-f512-49ed-893d-a8f61f25db98" Version="1.1" Language="en-US" Publisher="Olivier Guinart" />
Can you increment the version to 1.2? Thanks!

2017-09-23 19:10 UTC, OlivierGuinart commented
Good job! Just submitted my feedback for discussion\implementation. Tested with an older version of VS and it still works with VS2015 Community 😊 (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe).

Looking forward your updated PR and to push your changes into master.

Thanks!

Olivier.


From: Brian Peek [mailto:notifications@github.com]
Sent: Saturday, September 23, 2017 11:02 AM
To: OlivierGuinart/Merlin32Language <Merlin32Language@noreply.github.com>
Cc: OlivierGuinart <olivier_guinart+github@live.com>; Comment <comment@noreply.github.com>
Subject: Re: [OlivierGuinart/Merlin32Language] VS2017 support (#4)


The Shell.12.0 thing is a bit hacky (using a NuGet package someone created that has the proper DLL in it). You can perhaps avoid NuGet by using a redirection as described here: https://msdn.microsoft.com/en-us/magazine/mt493251.aspx but I haven't tested this. Happy to help if there's something else I can do! :)

Overall, I was just looking for 6502 syntax highlighting...using cc65 assembler and tools in a project, but this is close enough!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/OlivierGuinart/Merlin32Language/pull/4#issuecomment-331659230>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ALe73R3KxUhBI8_QbGxUHpj5IR13wwMAks5slUewgaJpZM4PhbE9>.

2017-09-23 19:11 UTC, BrianPeek commented
Cool, will update this weekend.  I guess maintaining the ref to 12.0 wasn’t necessary after all.  Had I known that I’d just have jumped to 15 and moved on.  Will update the PR today or tomorrow.  Thanks!

From: OlivierGuinart [mailto:notifications@github.com]
Sent: Saturday, September 23, 2017 3:10 PM
To: OlivierGuinart/Merlin32Language <Merlin32Language@noreply.github.com>
Cc: Brian Peek <brian@brianpeek.com>; Author <author@noreply.github.com>
Subject: Re: [OlivierGuinart/Merlin32Language] VS2017 support (#4)

Good job! Just submitted my feedback for discussion\implementation. Tested with an older version of VS and it still works with VS2015 Community 😊 (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe).

Looking forward your updated PR and to push your changes into master.

Thanks!

Olivier.


From: Brian Peek [mailto:notifications@github.com]
Sent: Saturday, September 23, 2017 11:02 AM
To: OlivierGuinart/Merlin32Language <Merlin32Language@noreply.github.com<mailto:Merlin32Language@noreply.github.com>>
Cc: OlivierGuinart <olivier_guinart+github@live.com<mailto:olivier_guinart+github@live.com>>; Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: Re: [OlivierGuinart/Merlin32Language] VS2017 support (#4)


The Shell.12.0 thing is a bit hacky (using a NuGet package someone created that has the proper DLL in it). You can perhaps avoid NuGet by using a redirection as described here: https://msdn.microsoft.com/en-us/magazine/mt493251.aspx but I haven't tested this. Happy to help if there's something else I can do! :)

Overall, I was just looking for 6502 syntax highlighting...using cc65 assembler and tools in a project, but this is close enough!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/OlivierGuinart/Merlin32Language/pull/4#issuecomment-331659230>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ALe73R3KxUhBI8_QbGxUHpj5IR13wwMAks5slUewgaJpZM4PhbE9>.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/OlivierGuinart/Merlin32Language/pull/4#issuecomment-331663691>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ACNtCzHHEHV74pw81Ukd43_cVGWUUQDmks5slVeWgaJpZM4PhbE9>.

2017-09-23 19:27 UTC, jmparis commented
Conversion to VS2017 done one month ago onto my fork.

2017-09-23 20:35 UTC, OlivierGuinart commented
Super Jean-Michel ! Anything we’re missing?

Merci !

Olivier.

From: Jean-Michel Paris [mailto:notifications@github.com]
Sent: Saturday, September 23, 2017 12:27 PM
To: OlivierGuinart/Merlin32Language <Merlin32Language@noreply.github.com>
Cc: OlivierGuinart <olivier_guinart+github@live.com>; Comment <comment@noreply.github.com>
Subject: Re: [OlivierGuinart/Merlin32Language] VS2017 support (#4)


Conversion to VS2017 done one month ago onto my fork.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/OlivierGuinart/Merlin32Language/pull/4#issuecomment-331664649>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ALe73Sly5SjrjERzZNaTij-kQ1qtedEsks5slVuQgaJpZM4PhbE9>.

2017-09-24 18:18 UTC, jmparis commented
I never did a PR on GitHub :) I Should have tried one month ago in order to save you time.

An absolute improvement to do is to add the labels defined in code, to the completion words list!

2017-09-24 20:21 UTC, BrianPeek commented
Made changes, add a .gitignore and removed some binaries and other junk.  I haven't tested this against anything earlier than VS2017.

2017-09-24 22:46 UTC, OlivierGuinart requested changes
About my yikes reaction, might not be a big deal if I get the opportunity to squash the commits at PR merge time :)

Please see missed to-be-removed references.

Thanks!

2017-09-24 22:46 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="Microsoft.VisualStudio.Threading, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
Reference to Microsoft.VisualStudio.Threading still in project file.

2017-09-24 22:46 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="System.Windows.Forms" />
Reference to System.Windows.Forms still in project file.

2017-09-24 22:46 UTC, OlivierGuinart commented on Merlin32Language.csproj
> +    <Reference Include="UIAutomationTypes" />
Reference to UIAutomationTypes still in project file.

2017-09-24 23:07 UTC, BrianPeek commented
I'll remove the refs.  I would suggest just doing a squash/merge on the PR which will only import the "final" version of the PR and not the "steps" in between.  You can enable squash merges in the repo settings.  Easier than trying to rewind time in git and you get a clean PR at the end of the process.

2017-09-24 23:22 UTC, OlivierGuinart commented
Sounds like a plan 😊

Thanks!

Olivier.

From: Brian Peek [mailto:notifications@github.com]
Sent: Sunday, September 24, 2017 4:07 PM
To: OlivierGuinart/Merlin32Language <Merlin32Language@noreply.github.com>
Cc: OlivierGuinart <olivier_guinart+github@live.com>; Comment <comment@noreply.github.com>
Subject: Re: [OlivierGuinart/Merlin32Language] VS2017 support (#4)


I'll remove the refs. I would suggest just doing a squash/merge on the PR which will only import the "final" version of the PR and not the "steps" in between. You can enable squash merges in the repo settings. Easier than trying to rewind time in git and you get a clean PR at the end of the process.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/OlivierGuinart/Merlin32Language/pull/4#issuecomment-331746594>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ALe73bjGOvIp5NsjJaOlUxf0mNk-UmHVks5sluCWgaJpZM4PhbE9>.

2017-09-26 02:33 UTC, OlivierGuinart approved these changes
I've tested with VS2015 :). Thank you!

2017-09-26 02:34 UTC, merged